### ISSUE TITLE
Overrides tag in .desktop files

### ISSUE THREAD

**Issue by sentaidigital** [linuxmint/cinnamon-menus#10]
Issue linuxmint/Cinnamon#2408 addresses the problem of having two System Settings icons show up in the same menu, one from Cinnamon, one from GNOME.  Two commits in this project, @9a306d1 and @c740513, address it by blacklisting anything that starts with "gnome-control-center."

This hard coded exclusion is what I would expect to be configuration data.  Hard coding the exclusion makes it more difficult to apply the same "use the Cinnamon version instead" logic to other applications.

Setting the OnlyShowIn to Cinnamon (or X-Cinnamon pending the freedesktop issue) prevents Cinnamon-specific items from showing in other DEs.  This is appropriate.  But, as Cinnamon is built on top of Gnome, we cannot just look for (X-)Cinnamon, but should display "OnlyShowIn: GNOME" as well.

The problem is that GNOME apps forked and optimized for Cinnamon should override the GNOME version.  The issue cited above handles a specific instance, but I have a hard time believing that the control center is the ONLY app that will run into this problem.

As a more general solution, would adding a tag to the .desktop file such as "Overrides: gnome-control-center*" work?  This would allow us to specify on a per-app basis which upstream items should be hidden, and not hard code the list.

**Comment by clefebvre** [comment]
It wouldn't be interpreted by other desktop environments.

Also, if you're talking about the XApps, they don't just override specific apps, they replace them. So if you install them, you can completely remove the other ones.

**Comment by sentaidigital** [comment]
> It wouldn't be interpreted by other desktop environments.

Yes, that is the expected behavior for two reasons: 1)  the .desktop files with `Overrides:` tags also have `OnlyShowIn: Cinnamon` tags and 2) other DEs don't grok the `Overrides:` tag.

> Also, if you're talking about the XApps, they don't just override specific apps, they replace them. So if you install them, you can completely remove the other ones.

Issue linuxmint/Cinnamon#2408 is specifically dealing with the case where two conflicting apps are installed *and the user cannot or does not want to uninstall either.*

Currently, the Gnome 3 shell will display the version of an app with `OnlyShowIn: Gnome` and ignore the System Settings with `OnlyShowIn: Cinnamon`.  Cinnamon will currently show *both* apps because it shows anything with `OnlyShowIn: Gnome` and `OnlyShowIn: Cinnamon`, but the `Overrides` tag would tell Cinnamon's menus to hide the Gnome version.  

Cinnamon has exceptions to the `OnlyShowIn: Gnome` rule hardcoded in an exception list.  The point of the `Overrides` tag is to move that exception list from code to data so other apps don't need to open a GitHub issue to get added to the exception list.

If you would prefer to name the tag `Replaces:`  (e.g., `Replaces: gnome-control-center`), that would be fine.  Telling users to uninstall the Gnome version is not.

**Comment by clefebvre** [comment]
I'd rather show both actually, and have the lib distinguish by extending the name when a collision is detected.

For instance, right now we see "Videos" and "Videos" when both Totem and Xplayer are installed, and "Videos" when only one of them is installed.

Instead, I'd like to see "Videos (xplayer)" and "Videos (totem)", or even "Videos" and "Videos (totem)" when both are installed. And "Videos" when only one of them is.

**Comment by sentaidigital** [comment]
Showing both with the name extended is a different use case and appropriate when an `Overrides:` or `Replaces:` tag is not present.
