### ISSUE TITLE
The menu is not synchronized with the cinnamon-settings

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon-menus#31]
![Снимак екрана од 2019-08-26 21-51-31](https://user-images.githubusercontent.com/38316957/63719234-c9c96700-c84c-11e9-96ea-3d1625243467.png)
![Снимак екрана од 2019-08-26 21-51-45](https://user-images.githubusercontent.com/38316957/63719235-c930d080-c84c-11e9-9548-3f78c3a53436.png)

**Comment by clefebvre** [comment]
In English please?
