### ISSUE TITLE
System settings, Administration and Preferences icons inconsistency

### ISSUE THREAD

**Issue by Silejonu** [linuxmint/cinnamon-menus#32]
Right now, the System settings, Administration and Preferences icons are inconsistent:
The Preferences menu is just the individual System settings entries. But they don't share the same icon, which they probably should, as they serve the same purpose, just showed differently.
What's worse is that the Administration menu share the same icon as the System settings, despite serving very different purposes. This makes things even more confusing.

Suggestion:
Have the Preferences (menu) & System settings (favourite) icons use the "preferences-system" icon.
Have the Administration (menu) use the "preferences-desktop" icon.

**Comment by clefebvre** [comment]
Agreed, but the other way around. They should match but continue the icon name that's meant for them. In our icon theme it's just a question of visual preference, but in other themes it could matter much more.
