### ISSUE TITLE
"Type to search" boilerplate appears in menu search box is not overwritten

### ISSUE THREAD

**Issue by asquartz** [linuxmint/cinnamon-menus#34]
What happens:
Occasionally, when I press the Cinnamon Menu panel button, the search bar in the menu contains the text "Type to search..." with the cursor to the right of this.  When I type a search term, my text appears to the right of the boilerplate, which is not overwritten.  See screenshot below.
[https://imgur.com/wfIvjGU](https://imgur.com/wfIvjGU)

What should happen:
When I open the menu, either the search box should be blank (usually the case for me) or the boilerplate text should be overwritten as soon as you start typing.

Reproducibility:
This seems to happen about 1 time in 10 for me.  I can't identify what factors trigger it though.

System info from inxi:
Kernel: 5.3.0-53-generic x86_64 bits: 64 
Desktop: Cinnamon 4.4.8 
Distro: Linux Mint 19.3 Tricia

**Comment by asquartz** [comment]
I don't know if anyone's reading these but I'd just like to add that following upgrade to Linux Mint 20 Ulyana, with Cinnamon 4.6.6, this problem still exists.

**Comment by Davidy22** [comment]
I have a quick fix [here](https://github.com/linuxmint/cinnamon/pull/10248) if it gets approved

**Comment by mtwebster** [comment]
Fixed: https://github.com/linuxmint/cinnamon/commit/769697eceea466c0eb24de0bf99dcb6beec26b8e
