### ISSUE TITLE
what package is needed to browsers bookmarks in Archlinux ?

### ISSUE THREAD

**Issue by PowaBanga** [linuxmint/cinnamon-menus#36]
Hi everybody.
I installed cinnamon-menu on my archlinux, and I want to use the browsers bookmarks feature.

The problem is that requiere gir1.2-gda-5.0 package to work. And this package do not exist on Archlinux. 
So I installed 
```
libgda
gobject-introspection
```
but this feature do not work in cinnamon-menu... :(

Does anybody can help me to find the good package please ?

**Comment by mtwebster** [comment]
I'm really not sure what you're talking about.  Are you using cinnamon?  Cinnamon-menus is a library, not an actual program.

Screenshot?

**Comment by PowaBanga** [comment]
Yes i am using cinnamon desktop.
https://www.archlinux.org/packages/community/x86_64/cinnamon/
!()[https://i.ibb.co/wp4TyQ4/Capture-d-cran-du-2020-07-01-15-21-56.png]

I do not know exactly what is this package : https://www.archlinux.org/packages/community/x86_64/cinnamon-menus/ I was thinking that is was the cinnamon menu...

**Comment by NikoKrause** [comment]
@PowaBanga You are using Cinnamenu, which is a third party applet. This is not officially supported by the Mint team. Maybe the maintainer of this applet @fredcw could help you out.

**Comment by fredcw** [comment]
@PowaBanga It seems this feature is no longer working even on linux mint with the right package installed, although it still works with Chrome bookmarks. As I'm not the original author of this code, I'm unable to fix it atm. I will take a look at it and see if I can fix it, but I can't make any promises as to when it might be working again.
