### ISSUE TITLE
Remove from favorites with right click option 'remove'

### ISSUE THREAD

**Issue by hrvoojex** [linuxmint/cinnamon-menus#5]
When you want to remove an item from favorites, you have to find it in a menu and then right click and select 'remove from favorites'. Yes, you can drag it from favorites to menu. If you drag it out of menu, nothing happens and this can be confusing for a new user.

Would it be possible to remove it right from the favorites menu with a right click or a mouse even if you move it out of the menu?

**Comment by clefebvre** [comment]
This should go in the "Cinnamon" project.

cinnamon-menus is a library... not the menu applet.
