### ISSUE TITLE
Cinnamon-menu-editor does not function in Python 3.10, fix included.

### ISSUE THREAD

**Issue by sp-merrow** [linuxmint/cinnamon-menus#56]
In cinnamon-menu-editor, on python 3.10 it will not open due to deprecation of importing the python collections module. Menu editor no longer opens on Arch Linux due to said deprecation.

To fix this issue:
In the python file utils.py in cinnamon-menu-editor, at line 22 replace "import collections" with "import collections.abc"

**Comment by leigh123linux** [comment]
@eli-schwartz Can you fix this please as I'm getting fed up with being spammed with the same issue. 

https://github.com/linuxmint/cinnamon/commit/749a4952b7d5ad6dd258017a3d13b47351148953

**Comment by ajgringo619** [comment]
> In cinnamon-menu-editor, on python 3.10 it will not open due to deprecation of importing the python collections module. Menu editor no longer opens on Arch Linux due to said deprecation.
> 
> To fix this issue: In the python file utils.py in cinnamon-menu-editor, at line 22 replace "import collections" with "import collections.abc"

Which file? My system is littered with utils.py files.
