### ISSUE TITLE
[FEATURE REQUEST] have an option to make cinnamon mintmenu function like a quick app launcher

### ISSUE THREAD

**Issue by jurassiclimecfg** [linuxmint/cinnamon-menus#60]
Hi, first of all a few apologies; firstly, this is my first time using github, so if I have done something stupid, that is why. Secondly, I hope this is the right place to suggest features for the menu, if not, could you please direct me to the right place so I can post it here instead. The forums suggest that I make a suggestion on the GitHub. Either way, your time is appreciated.

Could an option in the menu be implemented where it looks and functions like PowerToys Run on Windows or Alfred on macOS, where the menu is reduced to a search bar which comes up in the middle of the screen when they super key is pressed? I feel as if this would really improve my workflow. 

I have looked on the cinnamon extentions store, where I cannot see anything like this and I have already tried several alternatives on linux, which all didn't play very nice with cinnamon.

Thank you for all the great work you have done for linux mint

**Comment by fredcw** [comment]
Have you tried Ulauncher?

**Comment by JosephMcc** [comment]
On the main Cinnamon repo is usually best for this type of thing, but you did fine. This idea has been brought up before but I don't think there is currently any plans to implement anything like it. I'm surprised no one has ever tried to do this as an extension.

Just so you know, feature requests are routinely closed. It just helps to keep the issues cleaned up as much as we can.
