### ISSUE TITLE
Cinnamon Menu Editor not selecting custom image file for icons

### ISSUE THREAD

**Issue by andoruB** [linuxmint/cinnamon-menus#61]
Sorry if this is not the right place to post this issue, or if there's something wrong with my setup. Been having some issues with the menu editor for a few days now, whenever I add a new entry in the menu and I try to select a image file as an icon (be it png, bmp, ico, jpg, etc), it shows me this: 
![image](https://user-images.githubusercontent.com/4868784/181477570-6147f1eb-44c2-4d42-b2d6-179cacd3c28b.png)

I'm not able to press on "Select" to confirm my setting.
So then naturally I try to edit the desktop file, but I get this message:
![image](https://user-images.githubusercontent.com/4868784/181477840-5c135c22-4f51-4311-a88a-7e1465b0da6d.png)

Anyone have any idea what's causing this?

**Comment by JosephMcc** [comment]
The issue with the icon selection dialog is fixed in the newest Cinnamon 5.4. Outside of that can't be much help. You haven't provided much info. The best place to open cinnamon issues is: https://github.com/linuxmint/cinnamon/issues
