### ISSUE TITLE
Enable/Disable Categories

### ISSUE THREAD

**Issue by lucasgabmoreno** [linuxmint/cinnamon-menus#71]
It's there any possibilitie to add "enable/disable" categories personalization?

![image](https://github.com/linuxmint/cinnamon-menus/assets/83520011/88bdde54-c28c-41b4-b812-12cfb3834f61)

**Comment by fredcw** [comment]
You can do this in Cinnamenu applet. btw, menu applet is in Cinnamon repo.

**Comment by lucasgabmoreno** [comment]
> You can do this in Cinnamenu applet. btw, menu applet is in Cinnamon repo.

Cinnamenu doesnt show bar when Super key

**Comment by claudiux** [comment]
> 
> Cinnamenu doesnt show bar when Super key

Yes it does. You must remove the `menu@cinnamon.org` applet.

**Comment by leigh123linux** [comment]
You can remove categories with the menu editor in menu@cinnamon.org
