### ISSUE TITLE
Suggestion: Create a 'Remove' Option for Launchers in the Menus

### ISSUE THREAD

**Issue by RadicalRadish** [linuxmint/cinnamon-menus#9]
System Details:
Linux Kernel 3.16.0-38-generic
Linux Mint 17.2 x64 Cinnamon - Rafaela
Cinnamon 2.6.13
Nemo 2.6.7

===========================
As things stand just now if I want to remove a launcher from the Cinnamon's Menus I right-click on the launcher then I have only the option to "Uninstall" the launcher. Problem with this is that it seems that the system looks to uninstall packages associated with the launcher. I am a newbie in Linux and I have no idea what happens if a package gets uninstalled via this means. However, to save confusion, I think things would be improved if the right-click options included an option to simply "Remove the Launcher" (from the menus). In that way people don't risk landing with problems because they inadvertently uninstalled a package when all they wanted to do was remove a launcher.

Hope this suggestion is of help.

**Comment by KDB2** [comment]
@RadicalRadish 

Uninstall means clearly what it means. It means that you want to uninstall the software from your system. That the opposite of installing.  
Of course after uninstalling a software, you can't use it anymore.

If you want to hide a launcher, you can do it from the menu editor. Just unmark the launcher and it will not appear anymore in the Menu.

**Comment by JosephMcc** [comment]
I'm with KDB2 here. Uninstall seems pretty clear. If you want to edit entries that are shown in the menu thats exactly what the menu editor is for.
